name: Release Render

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create temporary branch
        run: |
          git checkout -b temp-release-branch

      - name: Commit changes
        run: |
          git add .
          git commit -m 'Release changes'

      - name: Push temporary branch
        run: |
          git push origin temp-release-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Release PR'
          body: 'This PR releases the changes to main.'
          base: main
          head: temp-release-branch
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-requests: write
